Script started on Thu 22 Nov 2018 03:48:11 PM PST
]0;jlaron@zuma:~/hw4[jlaron@zuma ~/hw4]$ make
gcc -ansi -std=c99 -Wall -c Test.c -o Test.o
gcc -ansi -std=c99 -Wall -c Image.c -o Image.o
gcc -ansi -std=c99 -Wall -c PhotoLab.c -o PhotoLab.o
gcc -ansi -std=c99 -Wall -c FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c  DIPs.c -o DIPs.o
gcc -ansi -std=c99 -Wall -c Advanced.c -o Advanced.o
ar rc libFilter.a Advanced.o DIPs.o
ranlib libFilter.a
gcc -ansi -std=c99 -Wall -lm Test.o Image.o PhotoLab.o FileIO.o -g -L. -lFilter -o PhotoLab
gcc -ansi -std=c99 -Wall -c -DDEBUG -c PhotoLab.c -o PhotoLab_DEBUG.o
gcc -ansi -std=c99 -Wall -lm Test.o Image.o PhotoLab_DEBUG.o FileIO.o -g -L. -lFilter -o PhotoLabTest
]0;jlaron@zuma:~/hw4[jlaron@zuma ~/hw4]$ ,[K./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Sketch the edge of an image
 5: Shuffle an image
 6: Adjust the brightness of an image
 7: Mirror an image horizontally
 8: Adjust the hue of an image
 9: Rotate or flip the image
 10: Resize the image
 11: Saturate the image
 12: Test all functions
 13: Exit
Please make your choice: 12
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
HSSOE.ppm was read.
brightness.ppm was saved. 
brightness.jpg was stored.
HSSOE.ppm was read.
hmirror.ppm was saved. 
hmirror.jpg was stored.
HSSOE.ppm was read.
hue.ppm was saved. 
hue.jpg was stored.
HSSOE.ppm was read.
rotate.ppm was saved. 
rotate.jpg was stored.
HSSOE.ppm was read.
hflip.ppm was saved. 
hflip.jpg was stored.
HSSOE.ppm was read.
smallresize.ppm was saved. 
smallresize.jpg was stored.
HSSOE.ppm was read.
bigresize.ppm was saved. 
bigresize.jpg was stored.
HSSOE.ppm was read.
saturate.ppm was saved. 
saturate.jpg was stored.

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Sketch the edge of an image
 5: Shuffle an image
 6: Adjust the brightness of an image
 7: Mirror an image horizontally
 8: Adjust the hue of an image
 9: Rotate or flip the image
 10: Resize the image
 11: Saturate the image
 12: Test all functions
 13: Exit
Please make your choice: 13
You exit the program.
]0;jlaron@zuma:~/hw4[jlaron@zuma ~/hw4]$ valgrind --leak-check=full ./PhotoLav[KbTest
==6804== Memcheck, a memory error detector
==6804== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==6804== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==6804== Command: ./PhotoLabTest
==6804== 
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
HSSOE.ppm was read.
brightness.ppm was saved. 
brightness.jpg was stored.
HSSOE.ppm was read.
hmirror.ppm was saved. 
hmirror.jpg was stored.
HSSOE.ppm was read.
hue.ppm was saved. 
hue.jpg was stored.
HSSOE.ppm was read.
rotate.ppm was saved. 
rotate.jpg was stored.
HSSOE.ppm was read.
hflip.ppm was saved. 
hflip.jpg was stored.
HSSOE.ppm was read.
smallresize.ppm was saved. 
smallresize.jpg was stored.
HSSOE.ppm was read.
bigresize.ppm was saved. 
bigresize.jpg was stored.
HSSOE.ppm was read.
saturate.ppm was saved. 
saturate.jpg was stored.
==6804== 
==6804== HEAP SUMMARY:
==6804==     in use at exit: 0 bytes in 0 blocks
==6804==   total heap usage: 94 allocs, 94 frees, 14,773,072 bytes allocated
==6804== 
==6804== All heap blocks were freed -- no leaks are possible
==6804== 
==6804== For counts of detected and suppressed errors, rerun with: -v
==6804== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;jlaron@zuma:~/hw4[jlaron@zuma ~/hw4]$ make clean
rm -f *.o *.jpg PhotoLab PhotoLabTest bw.ppm edge.ppm shuffle.ppm brightness.ppm hmirror.ppm hue.ppm  libFilter.a bigresize.ppm smallresize.ppm saturate.ppm hflip.ppm rotate.ppm Rotate.ppm rotater.ppm
]0;jlaron@zuma:~/hw4[jlaron@zuma ~/hw4]$ exit
exit

Script done on Thu 22 Nov 2018 03:49:24 PM PST
